# Thanks to https://github.com/coil-kt/coil/blob/master/.github/workflows/ci.yml

name: CI
on:
    pull_request:
jobs:
    ci:
        name: Build + Test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Checkout Gradle Build Cache
            if: ${{ steps.self_hosted.outputs.FLAG != 'self-hosted' }}
            uses: actions/cache@v2
            with:
              path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
                !~/.gradle/wrapper/dists/**/gradle*.zip
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
              restore-keys: |
                gradle-${{ runner.os }}-

          - name: Build
            run: ./gradlew clean build

          - name: Detekt
            run: ./gradlew detekt